---
- name: K8s Base Setup
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - preflight
    - base
    - repos
    - crio
    - k8s_packages

  tasks:
    - name: Reboot
      ansible.builtin.reboot:

