---
- name: Install CRI-O
  ansible.builtin.apt:
    name: "{{ k8s_crio_packages }}"
    state: present

- name: Enable and start CRI-O
  ansible.builtin.systemd_service:
    name: "{{ k8s_crio_service }}"
    state: started
    enabled: true
    daemon_reload: true
